

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .DS_Store
   - .idea
   - tests
   - CNAME
   - circle.yml
   - README.md
   - LICENSE.md
   - generate-tags.py
   - .gitignore
   - package.json
   - package-lock.json

markdown: kramdown
highlighter: rouge

kramdown:
   input: GFM
   syntax_highlighter: rouge
