name: Website

on:
  push:
    branches:    
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Applitools Eyes
      uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        baseUrl: https://www.kurmis.com/
